# Emotion configurations
emotion_modes:
  basic:
    emotions:
      - label: "POSITIVE"
        color: "#2ecc71"  # Green
        threshold: 0.5
      - label: "NEGATIVE" 
        color: "#e74c3c"  # Red
        threshold: 0.5
    model_config:
      top_k: 1
      threshold: 0.5

  standard:
    emotions:
      - label: "happiness"
        color: "#2ecc71"  # Green
        threshold: 0.3
      - label: "sadness"
        color: "#3498db"  # Blue
        threshold: 0.3
      - label: "anger"
        color: "#e74c3c"  # Red
        threshold: 0.3
      - label: "fear"
        color: "#9b59b6"  # Purple
        threshold: 0.3
      - label: "disgust"
        color: "#1abc9c"  # Turquoise
        threshold: 0.3
      - label: "surprise"
        color: "#f1c40f"  # Yellow
        threshold: 0.3
    model_config:
      top_k: 3
      threshold: 0.2

  detailed:
    emotions:
      # Primary emotions
      - label: "joy"
        variations: ["excited", "content", "proud", "relieved"]
        intensity_levels: ["slightly", "moderately", "very", "extremely"]
      - label: "sadness"
        variations: ["disappointed", "lonely", "hopeless", "grief"]
        intensity_levels: ["slightly", "moderately", "very", "extremely"]
      - label: "anger"
        variations: ["frustrated", "irritated", "outraged", "furious"]
        intensity_levels: ["slightly", "moderately", "very", "extremely"]
      - label: "fear"
        variations: ["anxious", "nervous", "terrified", "panicked"]
        intensity_levels: ["slightly", "moderately", "very", "extremely"]
      
      # Complex emotions
      - label: "bittersweet"
        combinations: ["joy", "sadness"]
      - label: "anxious-excitement"
        combinations: ["joy", "fear"]
      - label: "indignant"
        combinations: ["anger", "disgust"]
      
      # Neutral states
      - label: "neutral"
        variations: ["calm", "composed", "balanced"]
    
    analysis_config:
      segment_size: 50  # words per segment
      overlap: 10       # words overlap between segments
      threshold: 0.2    # emotion detection threshold